### ISSUE TITLE
Sending a command interrupts connexion to WS server and throws a JS error

### ISSUE THREAD

**Issue by sebescudie** [Edrig/OBS-Websocket-Chataigne-Module#25]
Hey there,

Here's my setup :

- Châtaigne 1.9.17b7
- OBS Websocket Châtaigne module 2.0.8
- OBS 29.1.3

I just added  the module to my project and was trying a bunch of commands in the Command Tester, but everytime I send a command, I'm getting those errors in the Log :

```
16:17:38.446	OBS Websocket	Connection closed
16:17:39.451	OBS Websocket	Connection opened
16:17:39.452	OBS	Script Error :
		Line 94, column 22 : Unknown function 'split'
```

See the following repro video

https://github.com/Edrig/OBS-Websocket-Chataigne-Module/assets/8690430/ec901d43-b957-42f1-85f1-fffb72de9bd6

Am I missing something?

Thanks!

**Comment by ChloeoeoeZ** [comment]
I'm getting the same error message.
Châtaigne 1.9.17
OBS Websocket Châtaigne module 2.0.8
OBS 30.0.2

Script Error :
Line 94, column 22 : Unknown function 'split'

**Comment by seanmcnally98** [comment]
Same issue here, Line 94, column 22 : Unknown function 'split'

**Comment by seanmcnally98** [comment]
So here's the thing, I know next to nothing about Javascript, but I was able to fix it by going into Chataigne\modules\OBS-Websocket-Chataigne-Module-main\OBS.js, and editing the function at line 94 to this:

`function toDecimal(v) {
    var decimal = 0;
    for (var i = 0; i < v.length; i++) {
        // Convert character to integer equivalent
        var digit = parseInt(v.charAt(i));
        // Check if the character is a valid binary digit
        if (isNaN(digit) || digit < 0 || digit > 1) {
            // If not a valid binary digit, return NaN (Not a Number)
            return NaN;
        }
        // Update the decimal value by multiplying by 2 and adding the binary digit
        decimal = (decimal * 2) + digit;
    }
    return decimal;
}`

Your mileage may vary, this worked for me but is definitely a temporary solution.

**Comment by Metarkice** [comment]
I don't know how the JS engine work in chataigne, but it seems that there's not all JS functions, including this one.

@tainalo2 the purpose of the function you wrote line 93 is to convert binary string to integer, right?
It doesn't seems to work properly even in a more standard JS engine (ex. a browser), because it use `.split()` instead of `split("")`

Anyway, looks like returning just `parseInt(v, 2);` is simpler and works fine in Chataigne.
